/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_minis_Minis */

#ifndef _Included_com_minis_Minis
#define _Included_com_minis_Minis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_minis_Minis
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_minis_Minis_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_minis_Minis
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_minis_Minis_nativeFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_minis_Minis
 * Method:    nativeSet
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_minis_Minis_nativeSet
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_minis_Minis
 * Method:    nativeGet
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_minis_Minis_nativeGet
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_minis_Minis
 * Method:    nativeDel
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_minis_Minis_nativeDel
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
